config/routes.rb
Cms::Application.routes.draw do

  devise_for :users

  namespace :admin do

    get "dashboard/index"
    get "dashboard/search"

    resources :pages
    resources :menus
    resources :news

  end

  root :to => 'admin::dashboard#index'

end

app/models/menu.rb
class Menu < ActiveRecord::Base
	acts_as_indexed :fields => [:name]

	has_and_belongs_to_many :pages

	attr_accessible :name, :page_ids
	validates :name, presence:true,
					length: {minimum: 3}
end

app/models/news.rb
require 'uri'

class News < ActiveRecord::Base

	acts_as_indexed :fields => [:title, :content]

	belongs_to :page
	attr_accessible :content, :image, :title, :page_id

	validates :title, presence: true,
						length: {minimum: 3}
	validates :content, presence: true
	validate :url_valid?
	validates :page_id, presence: true
	validates_associated :page

	default_value_for :title, 'I am THE title.'

	def url_valid?
		uri = URI.parse(self.image)
		if !uri.kind_of?(URI::HTTP) and !uri.kind_of?(URI::HTTPS) and !self.image.empty?
			errors.add :image, 'Wrong image URL!'
		end
	end
end

app/models/page.rb
class Page < ActiveRecord::Base

	acts_as_indexed :fields => [:title, :content]

	has_and_belongs_to_many :menus
	has_many :news

 	attr_accessible :content, :title, :menu_ids

	validates :title, presence: true, 
  					length: {minimum: 3, maximum:15 }
  	validates :content, presence:true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/admin/base_controller.rb
module Admin

	class BaseController < ApplicationController

		before_filter :require_login

		def require_login

			if current_user.nil?
				flash[:error] = 'You must be logged in.'
				redirect_to new_user_session_path
			end


		end

	end

end

app/controllers/admin/dashboard_controller.rb
module Admin

	class DashboardController < BaseController
	  def index
	  end

	  def search
	  	@search = params[:search]
	  	@results_page = Page.find_with_index(params[:search])
	  	@results_menu = Menu.find_with_index(params[:search])
	  	@results_news = News.find_with_index(params[:search])
	  end
	  	
	end
	
end

app/controllers/admin/menus_controller.rb
module Admin


	class MenusController < BaseController

		def index
			@menus = Menu.all
		end

		def new
			@menu = Menu.new
		end

		def create
			@menu = Menu.new params[:menu]
			if @menu.save
				flash[:success] = 'Menu created'
				redirect_to(admin_menus_path)
			else 
				render action: 'new'
			end
		end

		def destroy
			@menu = Menu.find params[:id]
			@menu.destroy
			flash[:success] = 'Menu deleted'
			redirect_to(admin_menus_path)
		end

		def edit
			@menu = Menu.find params[:id]
		end

		def update
			@menu = Menu.find params[:id]
			if @menu.update_attributes params[:menu]
				flash[:success] = 'Menu updated'
				redirect_to(admin_menus_path)
			else
				render action: 'edit'
			end
		end

		def show
			@menu = Menu.find params[:id]
		end

	end
	
end

app/controllers/admin/news_controller.rb
module Admin

	class NewsController < BaseController

		def index
			@news = News.all
		end

		def new
			@news = News.new
		end

		def create
			@news = News.new params[:news]
			if @news.save
				flash[:success] = 'News created'
				redirect_to(admin_news_index_path)
			else 
				render action: 'new'
			end
		end

		def destroy
			@news = News.find params[:id]
			@news.destroy
			flash[:success] = 'News deleted'
			redirect_to(admin_news_index_path)
		end

		def edit
			@news = News.find params[:id]
		end

		def update
			@news = News.find params[:id]
			if @news.update_attributes params[:news]
				flash[:success] = 'News updated'
				redirect_to(admin_news_index_path)
			else
				render action: 'edit'
			end
		end

		def show
			@news = News.find params[:id]
		end

	end

end

app/controllers/admin/pages_controller.rb
module Admin
	

	class PagesController < BaseController

		def index
			@pages = Page.all
		end

		def new
			@page = Page.new
		end

		def create
			@page = Page.new params[:page]
			if @page.save
				flash[:success] = 'Page created'
				redirect_to(admin_pages_path)
			else 
				render action: 'new'
			end
		end

		def destroy
			@page = Page.find params[:id]
			@page.destroy
			flash[:success] = 'Page deleted'
			redirect_to(admin_pages_path)
		end

		def edit
			@page = Page.find params[:id]
		end

		def update
			@page = Page.find params[:id]
			if @page.update_attributes params[:page]
				flash[:success] = 'Page updated'
				redirect_to(admin_pages_path)
			else
				render action: 'edit'
			end
		end

		def show
			@page = Page.find params[:id]
		end

	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  layout :layout
end
def layout
	if is_a?(Devise::SessionsController) or is_a?(Devise::RegistrationsController)
		return "app2"
	else 
		return "application"
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/admin/dashboard/index.html.erb
<h1>Dashboard</h1>
<ul>
	<li><%= link_to Page.all.count.to_s + ' Pages', admin_pages_path %></li>
	<li><%= link_to Menu.all.count.to_s + ' Menus', admin_menus_path %></li>
	<li><%= link_to News.all.count.to_s + ' News', admin_news_index_path %></li>
</ul>

app/views/admin/dashboard/search.html.erb
<% if @results_page.empty? %>
	<p>Pages: No results</p>
<% else %>
	<p>Pages: <%= pluralize(@results_page.count, 'result') %> found <%= link_to 'Useless Link All Pages', admin_pages_path %></p>
	<table>
		<tr>
			<th>ID</th>
			<th>Title</th>
			<th>Menus</th>
			<th>News</th>
			<th>Content</th>
			<th></th>
		</tr>
		<% @results_page.each do |page| %>
			<tr>
				<td><%= page.id %></td>
				<td><%= link_to highlight(page.title, @search), admin_page_path(page) %></td>
				<td><%=raw page.menus.map {|m| link_to m.name, admin_menu_path(m)}.join(', ') %></td>
				<td><%=raw page.news.map {|n| link_to n.title, admin_news_path(n)}.join(', ') %></td>
				<td><%= highlight(excerpt(page.content, @search, radius: 20), @search) %></td>
				<td><%= link_to 'Edit', edit_admin_page_path(page) %></td>	
			</tr>
		<% end %>
	</table>
<% end %>

<% if @results_menu.empty? %>
	<p>Menus: No results</p>
<% else %>
	<p>Menus: <%= @results_menu.count %> results found <%= link_to 'Useless Link All Menus', admin_menus_path %></p>

	<table>
		<tr>
			<th>ID</th>
			<th>Name</th>
			<th>Pages</th>
			<th></th>
			<th></th>

		</tr>
		<% @results_menu.each do |menu| %>
			<tr>
				<td><%= menu.id %></td>
				<td><%= link_to highlight(menu.name, @search), new_admin_menu_path(menu) %></td>
				<td><%=raw menu.pages.map {|p| link_to p.title, new_admin_page_path(p)}.join(', ') %></td>
				<td><%= link_to 'Delete', new_admin_menu_path(menu), confirm: 'Menu will be deleted!',
												method: :delete %></td>
				<td><%= link_to 'Edit', edit_admin_menu_path(menu) %></td>	
			</tr>
		<% end %>
	</table>
<% end %>

<% if @results_news.empty? %>
	<p>News: No results</p>
<% else %>
	<p>News: <%= @results_news.count %> results found <%= link_to 'Useless Link All News', admin_news_index_path %></p>

	<table>
		<tr>
			<th>ID</th>
			<th>Title</th>
			<th>Page</th>
			<th></th>
		</tr>
		<% @results_news.each do |news| %>
			<tr>
				<td><%= news.id %></td>
				<td><%= link_to highlight(news.title, @search), admin_news_path(news) %></td>
				<td><%= link_to news.page.title, admin_page_path(news.page) %></td>
				<td><%= highlight(excerpt(news.content, @search, radius: 20), @search) %></td>
				<td><%= link_to 'Edit', edit_admin_news_path(news) %></td>		
			</tr>
		<% end %>
	</table>
<% end %>

app/views/admin/menus/_form.html.erb
<%= simple_form_for(["admin", @menu]) do |f| %>
	<% if @menu.errors.any? %>
		<p>The form contains <%= pluralize(@menu.errors.count, "error") %>:</p>
	    <ul>
	    	<% @menu.errors.full_messages.each do |msg| %>
	    		<li class="error"><%= msg %></li>
	    	<% end %>
	    </ul>
	<% end %>
	<%= f.label :name %>
	<%= f.text_field :name %> <br>
	<%= f.association :pages, as: :check_boxes %>
	<%= link_to 'New Page', new_admin_page_path, class: 'small button' %> 
	<%= f.submit class: 'small button' %>






<% end %>

app/views/admin/menus/edit.html.erb
<h1>Edit Menu <%= @menu.name %></h1>
<%= render 'form' %>

app/views/admin/menus/index.html.erb
<h1>Menus</h1>
<%= link_to 'Create Menu', new_admin_menu_path, class: 'small button' %>
<table>
	<tr>
		<th>ID</th>
		<th>Name</th>
		<th>Pages</th>
		<th></th>
		<th></th>
		
		<th>Created</th>
		<th>Updated</th>

	</tr>
	<% @menus.each do |menu| %>
		<tr>
			<td><%= menu.id %></td>
			<td><%= link_to menu.name, new_admin_menu_path(menu) %></td>
			<td><%=raw menu.pages.map {|p| link_to p.title, new_admin_page_path(p)}.join(', ') %></td>
			<td><%= link_to 'Delete', new_admin_menu_path(menu), confirm: 'Menu will be deleted!',
											method: :delete %></td>
			<td><%= link_to 'Edit', edit_admin_menu_path(menu) %></td>

			<td><%= menu.created_at.strftime '%d. %m. %Y at %T UTC' %></td>
			<td><%= menu.updated_at.strftime '%d. %m. %Y at %T UTC' %></td>		
		</tr>
	<% end %>
</table>

app/views/admin/menus/new.html.erb
<h1>New menu</h1>
<%= render 'form' %>

app/views/admin/menus/show.html.erb
<h1><%= @menu.name %></h1>
<ul>
	<% @menu.pages.each do |page| %>
	<li><%= link_to page.title, admin_page_path(page) %></li>
	<% end %>
	</ul>
<p>Menu created: <%= @menu.created_at.strftime '%d. %m. %Y at %T UTC' %> | Last updated: 
	<%= @menu.updated_at.strftime '%d. %m. %Y at %T UTC' %></p>

app/views/admin/news/_form.html.erb
<%= simple_form_for(["admin",@news]) do |f| %>
	<% if @news.errors.any? %>
		<p>The form contains <%= pluralize(@news.errors.count, "error") %>:</p>
	    <ul>
	    	<% @news.errors.full_messages.each do |msg| %>
	    		<li class="error"><%= msg %></li>
	    	<% end %>
	    </ul>
	<% end %>
	<%= f.label :title %>
	<%= f.text_field :title %> <br>
	<%= f.label :content %>
	<%= f.text_area :content %> <br>
	<%= f.label :image %>
	<%= f.text_field :image %><br>
	<%= f.association :page %>
	<%= link_to 'New Page', new_admin_page_path, class: 'small button' %>
	<%= f.submit class: 'small button' %>






<% end %>

app/views/admin/news/edit.html.erb
<h1>Edit News <%= @news.title %></h1>
<%= render 'form' %>

app/views/admin/news/index.html.erb
<h1>News</h1>
<%= link_to 'Create News', new_admin_news_path, class: 'small button' %>
<table>
	<tr>
		<th>ID</th>
		<th>Title</th>
		<th>Page</th>
		<th></th>
		<th></th>
		<th>Created</th>
		<th>Updated</th>
	</tr>
	<% @news.each do |news| %>
		<tr>
			<td><%= news.id %></td>
			<td><%= link_to news.title, admin_news_path(news) %></td>
			<td><%= link_to news.page.title, admin_page_path(news.page) %></td>
			<td><%= link_to 'Delete', admin_news_path(news), confirm: 'News will be deleted!',
											method: :delete %></td>
			<td><%= link_to 'Edit', edit_admin_news_path(news) %></td>	
			<td><%= news.created_at.strftime '%d. %m. %Y at %T UTC' %></td>
			<td><%= news.updated_at.strftime '%d. %m. %Y at %T UTC' %></td>		
		</tr>
	<% end %>
</table>

app/views/admin/news/new.html.erb
<h1>New News</h1>
<%= render 'form' %>

app/views/admin/news/show.html.erb
<div class="news">
	<h1><%= @news.title %></h1>
	<p><%= @news.content %></p>
	<p>Page: <%= link_to @news.page.title, admin_page_path(@news.page) %></p>
	<% if @news.image !='' %>
		<img src="<%= @news.image %>" alt="<%= @news.title %>" />
	<% end %>
<p>News created: <%= @news.created_at.strftime '%d. %m. %Y at %T UTC' %> | Last updated: 
	<%= @news.updated_at.strftime '%d. %m. %Y at %T UTC' %></p>
</div>

app/views/admin/pages/_form.html.erb
<%= simple_form_for(["admin", @page]) do |f| %>
	<% if @page.errors.any? %>
		<p>The form contains <%= pluralize(@page.errors.count, "error") %>:</p>
	    <ul>
	    	<% @page.errors.full_messages.each do |msg| %>
	    		<li class="error"><%= msg %></li>
	    	<% end %>
	    </ul>
	<% end %>
	<%= f.label :title %>
	<%= f.text_field :title %> <br>
	<%= f.label :content %>
	<%= f.text_area :content %> <br>
	<%= f.association :menus, as: :check_boxes %>
	<%= link_to 'New Menu', new_admin_menu_path, class: 'small button' %>
	<%= f.submit class: 'small button' %>

<% end %>

app/views/admin/pages/edit.html.erb
<h1>Edit Page <%= @page.title %></h1>
<%= render 'form' %>

app/views/admin/pages/index.html.erb
<h1>Pages</h1>
<%= link_to 'Create Page', new_admin_page_path, class: 'small button'%>
<table>
	<tr>
		<th>ID</th>
		<th>Title</th>
		<th>Menus</th>
		<th>News</th>
		<th></th>
		<th></th>
		<th>Created</th>
		<th>Updated</th>
	</tr>
	<% @pages.each do |page| %>
		<tr>
			<td><%= page.id %></td>
			<td><%= link_to page.title, admin_page_path(page) %></td>
			<td><%=raw page.menus.map {|m| link_to m.name, admin_menu_path(m)}.join(', ') %></td>
			<td><%=raw page.news.map {|n| link_to n.title, admin_news_path(n)}.join(', ') %></td>
			<td><%= link_to 'Delete', admin_page_path(page), confirm: 'Page will be deleted!',
											method: :delete %></td>
			<td><%= link_to 'Edit', edit_admin_page_path(page) %></td>	
			<td><%= page.created_at.strftime '%d. %m. %Y at %T UTC' %></td>
			<td><%= page.updated_at.strftime '%d. %m. %Y at %T UTC' %></td>		
		</tr>
	<% end %>
</table>

app/views/admin/pages/new.html.erb
<h1>New page</h1>
<%= render 'form' %>

app/views/admin/pages/show.html.erb
<h1><%= @page.title %></h1>
	<p><%= @page.content.html_safe %></p>

<h2>This page can be accessed from this menus:</h2>
<ul>
	<% @page.menus.each do |menu| %>
	<li><%= link_to menu.name, admin_menu_path(menu) %></li>
	<% end %>
</ul>

<h2>News on this page:</h2>
<ul>
	<% @page.news.each do |news| %>
	<li><%= link_to news.title, admin_news_path(news) %></li>
	<% end %>
</ul>
<p>Page created: <%= @page.created_at.strftime '%d. %m. %Y at %T UTC' %> | Last updated: 
	<%= @page.updated_at.strftime '%d. %m. %Y at %T UTC' %></p>

app/views/layouts/app2.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
  	<meta charset="utf-8" />

  	<!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

  	<!-- Set the viewport width to device width for mobile -->
  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

  	<title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

  	<%= stylesheet_link_tag    "application" %>
  	<%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <nav class="top-bar">
      <ul class="title-area">
        <!-- Title Area -->
        <li class="name">
          <h1><a href="<%= root_path %>">Administration</a></h1>
        </li>
        <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
        <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
      </ul>
      <section class="top-bar-section">
        <!-- Right Nav Section -->
        <ul class="right">
          <li><%= link_to 'Dashboard', admin_dashboard_index_path %></li>
          <li><%= link_to 'Pages', admin_pages_path %></li>
          <li><%= link_to 'Menus', admin_menus_path %></li>
          <li><%= link_to 'News', admin_news_index_path %></li>

          <% if user_signed_in? %>
            <li><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>
            <% else %>
            <li><%= link_to 'Sign in', new_user_session_path %></li>
            <li><%= link_to 'Sign up', new_user_registration_path %></li>       
          <%end%>
        </ul>
      </section>
    </nav>

    <div class="row">
      <div class="small-6 small-centered large-centered columns">
        <% if flash.count > 0 %>
          <% flash.each do |key, value| %>
            <div data-alert class="alert-box">
              <%= value %>
              <a class="close">&times;</a>
            </div>
          <% end %>
          
        <% end %>

      </div>
    </div>
    <%= yield %>

    
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>Cms</title>
	  <%= stylesheet_link_tag    "application", :media => "all" %>
	  <%= javascript_include_tag "application" %>
	  <%= csrf_meta_tags %>
	</head>
	<body>
		<% if flash.count > 0 %>
		<ul>
			<% flash.each do |key, value| %>
				<li class="<%= key %>"><%= value %></li>
			<% end %>
		</ul>
		<% end %>
		<ul>
			<li><%= link_to 'Dashboard', dashboard_index_path %></li>
			<li><%= link_to 'Pages', pages_path %></li>
			<li><%= link_to 'Menus', menus_path %></li>
			<li><%= link_to 'News', news_index_path %></li>
		</ul>
		<%= yield %>

	</body>
</html>